name = "DataPipelineLocks"
uuid = "20753f05-dcde-462e-871d-030ce9b3c02b"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.2.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
